- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.0.24
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.0.24?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.0.25
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.0.25?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.0.26
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.0.26?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.1.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.1.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.10.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.10.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.11.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.11.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.12.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.12.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.2.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.2.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.3.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.3.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.4.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.4.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.5.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.5.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.6.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.6.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.7.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.7.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.8.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.8.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.8.1
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.8.1?classifier=sources
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.9.0
- pkg:maven/io.prometheus/simpleclient_jetty_jdk8@0.9.0?classifier=sources
