- pkg:maven/io.komune.fixers.gradle/config@0.17.0?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.18.0.beta.1?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.18.0?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.19.0.beta.1?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.19.0?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.20.0?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.21.0?classifier=sources
- pkg:maven/io.komune.fixers.gradle/config@0.22.0?classifier=sources
