- pkg:maven/fish.focus.uvms.docker/docker-compose@4.1.5?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.0?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.10?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.14?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.15?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.16?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.17?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.1?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.2?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.3?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.5?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.6?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.7?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.8?classifier=sources
- pkg:maven/fish.focus.uvms.docker/docker-compose@4.2.9?classifier=sources
