- pkg:maven/io.prometheus/prometheus-metrics-exporter-servlet-javax@1.2.0
- pkg:maven/io.prometheus/prometheus-metrics-exporter-servlet-javax@1.2.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-servlet-javax@1.2.1
- pkg:maven/io.prometheus/prometheus-metrics-exporter-servlet-javax@1.2.1?classifier=sources
