- pkg:maven/org.apache.dubbo/dubbo-metrics-prometheus@3.0.4
- pkg:maven/org.apache.dubbo/dubbo-metrics-prometheus@3.0.4?classifier=sources
- pkg:maven/org.apache.dubbo/dubbo-metrics-prometheus@3.0.5
- pkg:maven/org.apache.dubbo/dubbo-metrics-prometheus@3.0.5?classifier=sources
