- pkg:maven/com.malliina/netlify_3@1.6.45
- pkg:maven/com.malliina/netlify_3@1.6.45?classifier=sources
- pkg:maven/com.malliina/netlify_3@1.6.46
- pkg:maven/com.malliina/netlify_3@1.6.46?classifier=sources
