- pkg:maven/com.atombuilt.atomkt/config@1.0.0?classifier=sources
- pkg:maven/com.atombuilt.atomkt/config@1.0.1?classifier=sources
- pkg:maven/com.atombuilt.atomkt/config@1.0.2?classifier=sources
- pkg:maven/com.atombuilt.atomkt/config@2.0.0?classifier=sources
