- pkg:maven/org.apache.bookkeeper.stats/prometheus-metrics-provider@4.5.0
- pkg:maven/org.apache.bookkeeper.stats/prometheus-metrics-provider@4.5.0?classifier=sources
- pkg:maven/org.apache.bookkeeper.stats/prometheus-metrics-provider@4.5.1
- pkg:maven/org.apache.bookkeeper.stats/prometheus-metrics-provider@4.5.1?classifier=sources
- pkg:maven/org.apache.bookkeeper.stats/prometheus-metrics-provider@4.6.0
- pkg:maven/org.apache.bookkeeper.stats/prometheus-metrics-provider@4.6.0?classifier=sources
