- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-prometheus-spring-boot-autoconfigure@2.0.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-prometheus-spring-boot-autoconfigure@2.0.0-RELEASE?classifier=sources
