- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.2.0
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.2.0?classifier=sources
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.2.1
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.2.1?classifier=sources
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.0
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.0-M1
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.0-M1?classifier=sources
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.0-RC1
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.0-RC1?classifier=sources
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.0?classifier=sources
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.1
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.3.1?classifier=sources
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.4.0
- pkg:maven/io.awspring.cloud/spring-cloud-aws-docker-compose@3.4.0?classifier=sources
