- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.2
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.2?classifier=sources
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.3
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.3?classifier=sources
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.4
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.4?classifier=sources
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.5
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.5?classifier=sources
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.6
- pkg:maven/no.sysco.middleware.prometheus/kafka-client-collector@0.0.6?classifier=sources
