- pkg:maven/com.ovoenergy/meters4s-prometheus_2.12@1.3.2
- pkg:maven/com.ovoenergy/meters4s-prometheus_2.12@1.3.2?classifier=sources
- pkg:maven/com.ovoenergy/meters4s-prometheus_2.12@2.0.0
- pkg:maven/com.ovoenergy/meters4s-prometheus_2.12@2.0.0?classifier=sources
