- pkg:maven/com.expediagroup/dropwizard-prometheus-bundle@0.0.1
- pkg:maven/com.expediagroup/dropwizard-prometheus-bundle@0.0.1?classifier=sources
- pkg:maven/com.expediagroup/dropwizard-prometheus-bundle@0.0.2
- pkg:maven/com.expediagroup/dropwizard-prometheus-bundle@0.0.2?classifier=sources
- pkg:maven/com.expediagroup/dropwizard-prometheus-bundle@1.0.0
- pkg:maven/com.expediagroup/dropwizard-prometheus-bundle@1.0.0?classifier=sources
